"""Bounded ``test-backend-ops`` correctness hard-gate adapter for one typed case.

This adapter executes a verified ``test-backend-ops`` binary for exactly one filtered
set of operations against one named backend, parses the pinned ca94157 CSV result
grammar, applies a fail-closed correctness hard gate, and returns one versioned
:class:`BackendOpsSampleV1` through the caller-owned :class:`RunSession`. The grammar
is pinned to ``halo-box/strix-llama.cpp@ca94157f70a2776e8da6b6849b50b45a083d0478``
built with ``LLAMA_BUILD_TESTS=ON``.

Its only policy decision is fail-closed correctness: every selected case must be
exercised, supported, and free of an error message, and the child must exit
successfully. It defines no suite manifest, operation-set policy, ranking, or run
command; later layers call this adapter. It never acquires the GPU lock and never
finalizes the caller-owned ``RunSession``.
"""

from __future__ import annotations

import csv
import hashlib
import io
import re
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Annotated, Literal, Self, cast

from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    Field,
    StrictInt,
    StrictStr,
    ValidationError,
    model_validator,
)

from strixlab.adapters._executable_identity import (
    ExecutableIdentity,
    hash_executable,
    require_stable_executable,
)
from strixlab.evidence import RunSession
from strixlab.manifests import AbsolutePathString, DashId
from strixlab.process import ProcessOutcome, ProcessResult, run_process
from strixlab.serialization import canonical_json_bytes

__all__ = [
    "BackendOpsCapabilitiesV1",
    "BackendOpsCaseV1",
    "BackendOpsGateSummaryV1",
    "BackendOpsGrammarError",
    "BackendOpsInputsV1",
    "BackendOpsIntegrityError",
    "BackendOpsParseError",
    "BackendOpsRowV1",
    "BackendOpsSampleV1",
    "build_test_argv",
    "evaluate_gate",
    "parse_csv_rows",
    "parse_help_grammar",
    "parse_operations",
    "run_backend_ops_case",
]

# --- Pinned profile constants -------------------------------------------------

PROFILE: Literal["ca94157-v1"] = "ca94157-v1"
SOURCE_ANCHOR_COMMIT = "ca94157f70a2776e8da6b6849b50b45a083d0478"
EVIDENCE_ROLE = "correctness"
EVIDENCE_ROOT = "adapter/backend-ops"
STREAM_LIMIT_BYTES = 256 * 1024
EXPECTED_OPERATION_COUNT = 128
MAX_RESULT_ROWS = 4096
_BINARY_SUBJECT = "operations binary"

# The seven pinned upstream CSV columns, in order.
CSV_HEADER: tuple[str, ...] = (
    "backend_name",
    "op_name",
    "op_params",
    "test_mode",
    "supported",
    "error_message",
    "backend_reg_name",
)

# The pinned advertised mode and output vocabularies from the ca94157 usage text.
ADVERTISED_MODES: tuple[str, ...] = ("test", "grad", "perf", "support")
ADVERTISED_OUTPUTS: tuple[str, ...] = ("console", "sql", "csv")

# The pinned ca94157 ``--help`` usage and option-description grammar, one physical
# line per element. The single program-path token after ``Usage:`` is normalized
# before comparison; every other token must match exactly at whitespace-delimited
# boundaries. Kept verbatim from the exact-commit capture.
_PINNED_HELP_LINES: tuple[str, ...] = (
    "Usage: test-backend-ops [mode] [-o <op,..>] [-b <backend>] [-p <params regex>] [--output <console|sql|csv>] [--list-ops] [--show-coverage] [--test-file <path>] [-j <n>]",  # noqa: E501
    "    valid modes:",
    "      - test (default, compare with CPU backend for correctness)",
    "      - grad (compare gradients from backpropagation with method of finite differences)",
    "      - perf (performance evaluation)",
    "      - support (probe backend operation support)",
    "    op names for -o are as given by ggml_op_desc() (e.g. ADD, MUL_MAT, etc),",
    '        optionally including the full test case string (e.g. "ADD(type=f16,ne=[1,1,8,1],nr=[1,1,1,1],nf=1)")',  # noqa: E501
    "    --output specifies output format (default: console, options: console, sql, csv)",
    "    --list-ops lists all available GGML operations",
    "    --show-coverage shows test coverage",
    "    --test-file reads test operators from a test file generated by test-export-graph-ops",
    "    -j <n> runs tests using <n> parallel worker threads (default: 1, test mode only)",
)
_PINNED_HELP_TEXT = "\n".join(_PINNED_HELP_LINES) + "\n"

SampleStatus = Literal[
    "capability-failed",
    "capture-failed",
    "spawn-failed",
    "timed-out",
    "oversized-output",
    "encoding-failed",
    "child-failed",
    "parse-failed",
    "hard-gate-failed",
    "passed",
]
# A bounded reason that refines a capability failure without expanding the status set.
CapabilityReason = Literal[
    "help-exit",
    "help-stream",
    "help-grammar",
    "list-exit",
    "list-stream",
    "list-grammar",
    "operation-absent",
]
GateReason = Literal[
    "passed",
    "no-rows",
    "wrong-backend",
    "wrong-mode",
    "missing-operation",
    "unsupported-row",
    "error-bearing-row",
]
ErrorCategory = Literal[
    "none",
    "capture-failed",
    "spawn-failed",
    "timed-out",
    "output-oversized",
    "encoding-failed",
]
ProcessOutcomeLiteral = Literal["exited", "timed_out", "spawn_failed", "capture_failed"]

# Statuses reachable only after the test child ran (capabilities discovered).
_TEST_ONLY_STATUSES: frozenset[str] = frozenset(
    {"child-failed", "parse-failed", "hard-gate-failed", "passed"}
)

ProcessRunner = Callable[..., ProcessResult]


# --- Adapter exceptions -------------------------------------------------------


class BackendOpsIntegrityError(RuntimeError):
    """The verified binary drifted and can no longer be attested.

    This invalidates the whole operation: prior process evidence may remain, but no
    ``sample.json`` is written because no truthful binding can be claimed.
    """


class BackendOpsGrammarError(ValueError):
    """Captured ``--help`` or ``--list-ops`` output does not match the pinned grammar."""


class BackendOpsParseError(ValueError):
    """A ``test``-mode CSV output could not be normalized into result rows."""


# --- Typed v1 models ----------------------------------------------------------


class _Model(BaseModel):
    """Strict, frozen base for every v1 adapter model."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True, allow_inf_nan=False)


def _validate_case_id(value: str) -> str:
    if not (1 <= len(value) <= 64):
        raise ValueError("case id must be 1 to 64 characters")
    return value


def _validate_params_regex(value: str) -> str:
    if not value:
        raise ValueError("params_regex must be non-empty")
    if len(value.encode("utf-8")) > 512:
        raise ValueError("params_regex exceeds 512 UTF-8 bytes")
    if any(ord(character) < 0x20 or ord(character) == 0x7F for character in value):
        raise ValueError("params_regex must not contain C0 or DEL control characters")
    return value


def _validate_backend(value: str) -> str:
    if not (1 <= len(value) <= 128):
        raise ValueError("backend must be 1 to 128 characters")
    if any(not (0x20 <= ord(character) <= 0x7E) for character in value):
        raise ValueError("backend must be printable ASCII")
    return value


def _validate_build_id(value: str) -> str:
    encoded = value.encode("utf-8")
    if not (1 <= len(encoded) <= 256):
        raise ValueError("build_id must be 1 to 256 UTF-8 bytes")
    if any(ord(character) < 0x20 or ord(character) == 0x7F for character in value):
        raise ValueError("build_id must not contain C0 or DEL control characters")
    return value


CaseId = Annotated[DashId, AfterValidator(_validate_case_id)]
OperationName = Annotated[str, Field(pattern=r"^[A-Z][A-Z0-9_]*$")]
ParamsRegex = Annotated[StrictStr, AfterValidator(_validate_params_regex)]
BackendSelector = Annotated[StrictStr, AfterValidator(_validate_backend)]
BuildId = Annotated[StrictStr, AfterValidator(_validate_build_id)]
Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{64}$")]
NonNegativeInt = Annotated[StrictInt, Field(ge=0)]
NonNegativeFloat = Annotated[float, Field(ge=0)]
PositiveInt = Annotated[StrictInt, Field(ge=1)]


class BackendOpsCaseV1(_Model):
    """One typed correctness case: a filtered operation set against one backend."""

    schema_version: Literal[1] = 1
    id: CaseId
    operations: Annotated[tuple[OperationName, ...], Field(min_length=1, max_length=32)]
    params_regex: ParamsRegex
    backend: BackendSelector
    mode: Literal["test"] = "test"
    output: Literal["csv"] = "csv"
    parallel_workers: Literal[1] = 1

    @model_validator(mode="after")
    def _unique_operations(self) -> Self:
        if len(set(self.operations)) != len(self.operations):
            raise ValueError("operations must be unique")
        return self


class BackendOpsInputsV1(_Model):
    """Verified binary provenance bound to one correctness case.

    The binary is supplied and verified by the trusted caller; a producing build
    profile must include ``LLAMA_BUILD_TESTS=ON``. This adapter re-verifies executable
    identity but never builds.
    """

    schema_version: Literal[1] = 1
    source_commit: Literal["ca94157f70a2776e8da6b6849b50b45a083d0478"] = (
        "ca94157f70a2776e8da6b6849b50b45a083d0478"
    )
    build_id: BuildId
    binary_path: AbsolutePathString
    binary_sha256: Sha256Hex


class BackendOpsCapabilitiesV1(_Model):
    """The parsed ca94157-v1 capability profile: output grammar and operation tuple."""

    schema_version: Literal[1] = 1
    profile: Literal["ca94157-v1"] = PROFILE
    binary_sha256: Sha256Hex
    modes: tuple[str, ...] = ADVERTISED_MODES
    output_choices: tuple[str, ...] = ADVERTISED_OUTPUTS
    operations: Annotated[
        tuple[OperationName, ...],
        Field(min_length=EXPECTED_OPERATION_COUNT, max_length=EXPECTED_OPERATION_COUNT),
    ]

    @model_validator(mode="after")
    def _unique_operations(self) -> Self:
        if len(set(self.operations)) != len(self.operations):
            raise ValueError("advertised operations must be unique")
        return self


class ProcessProjectionV1(_Model):
    """Neutral projection of one child :class:`ProcessResult`.

    ``error_category`` records only process-level defects across both streams;
    return-code semantics are contract-specific and evaluated separately. No raw
    exception prose is ever carried.
    """

    schema_version: Literal[1] = 1
    outcome: ProcessOutcomeLiteral
    returncode: int | None
    duration_seconds: NonNegativeFloat
    stdout_bytes: NonNegativeInt
    stderr_bytes: NonNegativeInt
    stdout_sha256: Sha256Hex
    stderr_sha256: Sha256Hex
    stdout_truncated: bool
    stderr_truncated: bool
    stdout_publishable: bool
    stderr_publishable: bool
    error_category: ErrorCategory


class BackendOpsCapabilityAttemptV1(_Model):
    """Capability status plus complete help/list-ops process projections."""

    schema_version: Literal[1] = 1
    status: Literal["discovered", "failed"]
    reason: CapabilityReason | None
    help: ProcessProjectionV1
    list_ops: ProcessProjectionV1
    capabilities: BackendOpsCapabilitiesV1 | None

    @model_validator(mode="after")
    def _consistent(self) -> Self:
        if self.status == "discovered":
            if self.capabilities is None or self.reason is not None:
                raise ValueError("a discovered attempt carries capabilities and no reason")
        elif self.capabilities is not None:
            raise ValueError("a failed attempt carries no capabilities")
        return self


class BackendOpsRowV1(_Model):
    """One parsed CSV result row with all seven upstream columns."""

    schema_version: Literal[1] = 1
    backend_name: StrictStr
    op_name: StrictStr
    op_params: StrictStr
    test_mode: StrictStr
    supported: Literal["0", "1"]
    error_message: StrictStr
    backend_reg_name: StrictStr


class BackendOpsGateSummaryV1(_Model):
    """The terminal hard-gate decision over the parsed rows."""

    schema_version: Literal[1] = 1
    selected_count: PositiveInt
    observed_rows: NonNegativeInt
    observed_backends: tuple[str, ...]
    passed: bool
    reason: GateReason

    @model_validator(mode="after")
    def _consistent(self) -> Self:
        if self.passed != (self.reason == "passed"):
            raise ValueError("gate.passed must agree with the passed reason")
        return self


class BackendOpsInvocationV1(_Model):
    """Exact test-mode argv, ordinal, fixed mode/output, and process projection."""

    schema_version: Literal[1] = 1
    ordinal: PositiveInt
    argv: tuple[StrictStr, ...]
    mode: Literal["test"] = "test"
    output: Literal["csv"] = "csv"
    process: ProcessProjectionV1


class BackendOpsArtifactV1(_Model):
    """One evidence artifact written before the terminal sample."""

    path: StrictStr
    size_bytes: NonNegativeInt
    media_type: StrictStr
    role: StrictStr
    sha256: Sha256Hex


class BackendOpsSampleV1(_Model):
    """The terminal, versioned adapter sample for one correctness case."""

    schema_version: Literal[1] = 1
    profile: Literal["ca94157-v1"] = PROFILE
    status: SampleStatus
    reason: CapabilityReason | None
    case: BackendOpsCaseV1
    inputs: BackendOpsInputsV1
    capability_attempt: BackendOpsCapabilityAttemptV1
    capabilities: BackendOpsCapabilitiesV1 | None
    invocation: BackendOpsInvocationV1 | None
    rows: tuple[BackendOpsRowV1, ...] | None
    gate: BackendOpsGateSummaryV1 | None
    artifacts: tuple[BackendOpsArtifactV1, ...]

    @model_validator(mode="after")
    def _consistent(self) -> Self:
        if self.capabilities != self.capability_attempt.capabilities:
            raise ValueError("sample capabilities must mirror the capability attempt")
        if self.reason != self.capability_attempt.reason:
            raise ValueError("sample reason must mirror the capability attempt reason")
        if (self.reason is not None) != (self.status == "capability-failed"):
            raise ValueError("a reason refines exactly a capability failure")
        # ``capabilities`` presence already follows from the mirror above and the
        # attempt's own discovered-iff-capabilities invariant, so only the
        # invocation and status couplings remain to check here.
        discovered = self.capability_attempt.status == "discovered"
        if discovered != (self.invocation is not None):
            raise ValueError("an invocation exists exactly when capabilities were discovered")
        if not discovered and self.status in _TEST_ONLY_STATUSES:
            raise ValueError("a test-child status requires discovered capabilities")
        if (
            self.status in _TEST_ONLY_STATUSES
            and self.invocation is not None
            and self.invocation.process.error_category != "none"
        ):
            raise ValueError("a post-parse status requires a test process with no defect")
        if self.status in ("passed", "hard-gate-failed"):
            if self.gate is None or self.rows is None:
                raise ValueError("a gated sample binds rows and a gate summary")
            if (self.status == "passed") != self.gate.passed:
                raise ValueError("gate.passed must agree with the passed status")
        elif self.gate is not None:
            raise ValueError("only a gated sample carries a gate summary")
        if self.status == "parse-failed" and self.rows is not None:
            raise ValueError("a parse-failed sample retains no rows")
        return self


# --- Pure command builder -----------------------------------------------------


def build_test_argv(*, binary_path: str, case: BackendOpsCaseV1) -> tuple[str, ...]:
    """Return the only allowlisted argv for one test-mode CSV invocation.

    Every value is read from the typed case, so injection-shaped ``params_regex`` or
    backend values remain single argv data items and never become shell text.
    """

    # Fully revalidate the case, rejecting any value (operations, backend, regex, or the
    # fixed mode/output/workers) that cannot round-trip through the typed case — for
    # example a case built via ``model_construct`` that bypassed validation.
    try:
        BackendOpsCaseV1.model_validate(case.model_dump())
    except ValidationError as exc:
        raise ValueError("case does not round-trip to the pinned test-mode invocation") from exc
    return (
        binary_path,
        "test",
        "-o",
        ",".join(case.operations),
        "-b",
        case.backend,
        "-p",
        case.params_regex,
        "--output",
        "csv",
        "-j",
        "1",
    )


# --- Pure capability parsers --------------------------------------------------


def _help_token_lines(text: str) -> tuple[tuple[str, ...], ...]:
    """Tokenize each nonempty stripped help line at whitespace boundaries."""

    lines: list[tuple[str, ...]] = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped:
            lines.append(tuple(stripped.split()))
    return tuple(lines)


_PINNED_HELP_TOKENS = _help_token_lines(_PINNED_HELP_TEXT)


def parse_help_grammar(help_stdout: str) -> bool:
    """Return whether ``help_stdout`` matches the pinned ca94157 usage grammar.

    Only the single non-whitespace program-path token after ``Usage:`` is normalized;
    every other token must match the pinned grammar exactly. Suffix, substring,
    reordered-option, and weakened-choice lookalikes therefore fail.
    """

    observed = _help_token_lines(help_stdout)
    if not observed:
        return False
    first = observed[0]
    if len(first) < 2 or first[0] != "Usage:":
        return False
    normalized_first = (first[0], _PINNED_HELP_TOKENS[0][1]) + first[2:]
    return ((normalized_first, *observed[1:])) == _PINNED_HELP_TOKENS


def parse_operations(list_stdout: str) -> tuple[str, ...]:
    """Parse the exact ca94157 ``--list-ops`` header/list/blank/total grammar.

    Requires exactly ``EXPECTED_OPERATION_COUNT`` unique two-space-indented uppercase
    operation lines and the matching ``Total`` line; any drift raises
    :class:`BackendOpsGrammarError` rather than silently forward-compatible parsing.
    """

    if "\r" in list_stdout or not list_stdout.endswith("\n"):
        raise BackendOpsGrammarError("operation list has an unexpected line ending")
    # The trailing newline guarantees a final empty split element to drop.
    lines = list_stdout.split("\n")[:-1]
    if len(lines) != EXPECTED_OPERATION_COUNT + 3:
        raise BackendOpsGrammarError("operation list has an unexpected line count")
    if lines[0] != "GGML operations:":
        raise BackendOpsGrammarError("operation list is missing its header")
    if lines[EXPECTED_OPERATION_COUNT + 1] != "":
        raise BackendOpsGrammarError("operation list is missing its blank separator")
    if lines[EXPECTED_OPERATION_COUNT + 2] != f"Total: {EXPECTED_OPERATION_COUNT} operations":
        raise BackendOpsGrammarError("operation list has an unexpected total line")
    operations: list[str] = []
    seen: set[str] = set()
    for line in lines[1 : EXPECTED_OPERATION_COUNT + 1]:
        name = line[2:]
        if line != "  " + name or re.fullmatch(r"[A-Z][A-Z0-9_]*", name) is None:
            raise BackendOpsGrammarError("operation list has a malformed operation line")
        if name in seen:
            raise BackendOpsGrammarError("operation list has a duplicate operation")
        seen.add(name)
        operations.append(name)
    return tuple(operations)


# --- Pure CSV parser ----------------------------------------------------------


def parse_csv_rows(stdout: str, *, case: BackendOpsCaseV1) -> tuple[BackendOpsRowV1, ...]:
    """Parse and structurally validate one test-mode CSV output, preserving row order.

    Uses the standard-library reader in strict mode over complete UTF-8 stdout and
    rejects a wrong header, malformed quoting or column counts, blank or newline-
    bearing records, trailing content, control characters, an out-of-range row count,
    a non-``test`` mode, an unrequested operation, a mismatched or empty backend, a
    non-pinned ``supported`` value, and duplicate rows. Any ``csv.Error`` (including
    the default field-size limit) becomes a domain parse error.
    """

    if "\r" in stdout:
        raise BackendOpsParseError("CSV output contains a carriage return")
    reader = csv.reader(io.StringIO(stdout, newline=""), strict=True)
    try:
        records = list(reader)
    except csv.Error as exc:
        raise BackendOpsParseError("CSV output is malformed") from exc
    if not records:
        raise BackendOpsParseError("CSV output is empty")
    header, *data = records
    if tuple(header) != CSV_HEADER:
        raise BackendOpsParseError("CSV header does not match the pinned columns")
    if not data:
        raise BackendOpsParseError("CSV output has zero result rows")
    if len(data) > MAX_RESULT_ROWS:
        raise BackendOpsParseError("CSV output exceeds the maximum row count")

    requested = set(case.operations)
    seen: set[tuple[str, ...]] = set()
    rows: list[BackendOpsRowV1] = []
    for record in data:
        if record == []:
            raise BackendOpsParseError("CSV output contains a blank record")
        if len(record) != len(CSV_HEADER):
            raise BackendOpsParseError("CSV row has the wrong column count")
        for field_value in record:
            if any(ord(ch) < 0x20 or ord(ch) == 0x7F for ch in field_value):
                raise BackendOpsParseError("CSV field contains a control character")
        identity = tuple(record)
        if identity in seen:
            raise BackendOpsParseError("CSV output contains a duplicate row")
        seen.add(identity)
        (backend_name, op_name, op_params, test_mode, supported, error_message, reg_name) = record
        if test_mode != "test":
            raise BackendOpsParseError("CSV row is not a test-mode row")
        if op_name not in requested:
            raise BackendOpsParseError("CSV row reports an unrequested operation")
        if backend_name == "" or backend_name != case.backend:
            raise BackendOpsParseError("CSV row backend does not match the requested backend")
        if supported not in ("0", "1"):
            raise BackendOpsParseError("CSV row has a non-pinned supported value")
        rows.append(
            BackendOpsRowV1(
                backend_name=backend_name,
                op_name=op_name,
                op_params=op_params,
                test_mode=test_mode,
                supported=cast(Literal["0", "1"], supported),
                error_message=error_message,
                backend_reg_name=reg_name,
            )
        )
    return tuple(rows)


# --- Pure hard-gate policy ----------------------------------------------------


def evaluate_gate(
    rows: tuple[BackendOpsRowV1, ...], *, case: BackendOpsCaseV1
) -> BackendOpsGateSummaryV1:
    """Decide fail-closed correctness over already-parsed rows.

    A case passes only when there is at least one row, every row binds the requested
    backend and test mode, every requested operation appears in at least one row,
    every row is supported (``"1"``), and every ``error_message`` is empty.
    """

    observed_backends: list[str] = []
    for row in rows:
        if row.backend_name not in observed_backends:
            observed_backends.append(row.backend_name)
    reason = _gate_reason(rows, case)
    return BackendOpsGateSummaryV1(
        selected_count=len(case.operations),
        observed_rows=len(rows),
        observed_backends=tuple(observed_backends),
        passed=reason == "passed",
        reason=reason,
    )


def _gate_reason(rows: tuple[BackendOpsRowV1, ...], case: BackendOpsCaseV1) -> GateReason:
    if not rows:
        return "no-rows"
    if any(row.backend_name != case.backend for row in rows):
        return "wrong-backend"
    if any(row.test_mode != "test" for row in rows):
        return "wrong-mode"
    observed_operations = {row.op_name for row in rows}
    if any(operation not in observed_operations for operation in case.operations):
        return "missing-operation"
    if any(row.supported != "1" for row in rows):
        return "unsupported-row"
    if any(row.error_message != "" for row in rows):
        return "error-bearing-row"
    return "passed"


# --- Binary integrity ---------------------------------------------------------


def _hash_binary(path: Path) -> ExecutableIdentity:
    """Stream-hash a non-symlink regular executable with pre/post metadata stability."""

    return hash_executable(path, error=BackendOpsIntegrityError, subject=_BINARY_SUBJECT)


def _require_stable_binary(path: Path, expected: ExecutableIdentity) -> ExecutableIdentity:
    return require_stable_executable(
        path, expected, error=BackendOpsIntegrityError, subject=_BINARY_SUBJECT
    )


# --- Process projection and stream exactness ---------------------------------

_OUTCOME_NAMES: dict[ProcessOutcome, ProcessOutcomeLiteral] = {
    ProcessOutcome.EXITED: "exited",
    ProcessOutcome.TIMED_OUT: "timed_out",
    ProcessOutcome.SPAWN_FAILED: "spawn_failed",
    ProcessOutcome.CAPTURE_FAILED: "capture_failed",
}


@dataclass(frozen=True, slots=True)
class _ProjectedProcess:
    projection: ProcessProjectionV1
    stdout_text: str | None
    stderr_text: str | None


def _exact_stream(text: str, byte_count: int, sha256: str, truncated: bool) -> str | None:
    """Return the publishable text of an exact stream, or ``None`` when inexact.

    A stream is exact only when it is not truncated and re-encoding the returned text
    as UTF-8 reproduces both the recorded byte count and SHA-256.
    """

    if truncated:
        return None
    encoded = text.encode("utf-8")
    if len(encoded) == byte_count and hashlib.sha256(encoded).hexdigest() == sha256:
        return text
    return None


def _project(result: ProcessResult) -> _ProjectedProcess:
    stdout_text = _exact_stream(
        result.stdout, result.stdout_bytes, result.stdout_sha256, result.stdout_truncated
    )
    stderr_text = _exact_stream(
        result.stderr, result.stderr_bytes, result.stderr_sha256, result.stderr_truncated
    )
    stdout_publishable = stdout_text is not None
    stderr_publishable = stderr_text is not None
    return _ProjectedProcess(
        projection=ProcessProjectionV1(
            outcome=_OUTCOME_NAMES[result.outcome],
            returncode=result.returncode,
            duration_seconds=max(0.0, result.duration),
            stdout_bytes=result.stdout_bytes,
            stderr_bytes=result.stderr_bytes,
            stdout_sha256=result.stdout_sha256,
            stderr_sha256=result.stderr_sha256,
            stdout_truncated=result.stdout_truncated,
            stderr_truncated=result.stderr_truncated,
            stdout_publishable=stdout_publishable,
            stderr_publishable=stderr_publishable,
            error_category=_error_category(
                result,
                stdout_publishable=stdout_publishable,
                stderr_publishable=stderr_publishable,
            ),
        ),
        stdout_text=stdout_text,
        stderr_text=stderr_text,
    )


def _error_category(
    result: ProcessResult, *, stdout_publishable: bool, stderr_publishable: bool
) -> ErrorCategory:
    if result.outcome is ProcessOutcome.CAPTURE_FAILED:
        return "capture-failed"
    if result.outcome is ProcessOutcome.SPAWN_FAILED:
        return "spawn-failed"
    if result.outcome is ProcessOutcome.TIMED_OUT:
        return "timed-out"
    if result.stdout_truncated or result.stderr_truncated:
        return "output-oversized"
    if not stdout_publishable or not stderr_publishable:
        return "encoding-failed"
    return "none"


# --- Evidence writer ----------------------------------------------------------


@dataclass(slots=True)
class _CaseEvidence:
    """Writes deterministic portable evidence under one case namespace.

    Every artifact written before the terminal sample is recorded so the sample can
    inventory it. ``sample.json`` is written through :meth:`sample` and is excluded
    from its own inventory.
    """

    run: RunSession
    base: str
    written: list[BackendOpsArtifactV1] = field(default_factory=list)

    def _publish(self, relative: str, content: bytes, *, media_type: str) -> None:
        entry = self.run.write_portable(
            f"{self.base}/{relative}", content, media_type=media_type, role=EVIDENCE_ROLE
        )
        self.written.append(
            BackendOpsArtifactV1(
                path=entry.logical_path,
                size_bytes=entry.size_bytes,
                media_type=entry.media_type,
                role=entry.role,
                sha256=entry.blob_sha256,
            )
        )

    def json(self, relative: str, value: object) -> None:
        self._publish(relative, canonical_json_bytes(value), media_type="application/json")

    def streams(
        self,
        prefix: str,
        process: _ProjectedProcess,
        *,
        sep: str,
        stdout_name: str,
        stdout_media: str,
    ) -> None:
        """Publish nonempty exact stdout/stderr text and the process projection.

        Truncated or non-UTF-8 streams have no text artifact; ``process.json`` still
        preserves their complete byte counts, digests, truncation, and neutral
        category. An exact stdout is published even when the exact stderr is not, and
        vice versa. A zero-byte exact stream carries no more than its already-recorded
        digest, so no empty text blob is written — this also keeps the shared empty
        blob from colliding across the ``text/plain`` and ``text/csv`` media types.
        """

        if process.stdout_text:
            self._publish(
                f"{prefix}{sep}{stdout_name}",
                process.stdout_text.encode("utf-8"),
                media_type=stdout_media,
            )
        if process.stderr_text:
            self._publish(
                f"{prefix}{sep}stderr.txt",
                process.stderr_text.encode("utf-8"),
                media_type="text/plain",
            )
        self.json(f"{prefix}{sep}process.json", process.projection.model_dump(mode="json"))

    def sample(self, value: object) -> None:
        """Write the terminal ``sample.json`` last, excluded from its own inventory."""

        self.run.write_portable(
            f"{self.base}/sample.json",
            canonical_json_bytes(value),
            media_type="application/json",
            role=EVIDENCE_ROLE,
        )


def _run_child(
    *,
    runner: ProcessRunner,
    argv: tuple[str, ...],
    cwd: Path,
    timeout: float,
    environment: Mapping[str, str],
    evidence: _CaseEvidence,
    prefix: str,
    sep: str,
    stdout_name: str,
    stdout_media: str,
) -> _ProjectedProcess:
    result = runner(
        argv,
        cwd=cwd,
        timeout=timeout,
        inherit_env=False,
        base_env=environment,
        output_limit_bytes=STREAM_LIMIT_BYTES,
    )
    projected = _project(result)
    evidence.streams(prefix, projected, sep=sep, stdout_name=stdout_name, stdout_media=stdout_media)
    return projected


# --- Capability and test-child classification ---------------------------------

# Process-defect precedence shared by both probes; ties select help before list-ops.
_PROBE_DEFECT_ORDER: tuple[ErrorCategory, ...] = (
    "capture-failed",
    "spawn-failed",
    "timed-out",
    "output-oversized",
    "encoding-failed",
)
_DEFECT_STATUS: dict[ErrorCategory, SampleStatus] = {
    "capture-failed": "capture-failed",
    "spawn-failed": "spawn-failed",
    "timed-out": "timed-out",
    "output-oversized": "oversized-output",
    "encoding-failed": "encoding-failed",
}


def _probe_defect(
    help_projection: ProcessProjectionV1, list_projection: ProcessProjectionV1
) -> SampleStatus | None:
    for category in _PROBE_DEFECT_ORDER:
        if help_projection.error_category == category:
            return _DEFECT_STATUS[category]
        if list_projection.error_category == category:
            return _DEFECT_STATUS[category]
    return None


def _probe_streams_clean(projection: ProcessProjectionV1) -> bool:
    """A probe's streams are clean when stdout is exact and stderr is exact and empty."""

    return (
        projection.stdout_publishable
        and projection.stderr_publishable
        and projection.stderr_bytes == 0
    )


def _evaluate_capability(
    help_process: _ProjectedProcess,
    list_process: _ProjectedProcess,
    *,
    case: BackendOpsCaseV1,
    binary_sha256: str,
) -> tuple[SampleStatus | None, CapabilityReason | None, BackendOpsCapabilitiesV1 | None]:
    """Decide whether both probes prove the pinned capability profile.

    Returns a terminal process-defect status (no reason), or a ``capability-failed``
    status with a refining reason, or ``(None, None, capabilities)`` when discovered.
    """

    defect = _probe_defect(help_process.projection, list_process.projection)
    if defect is not None:
        return defect, None, None

    help_projection = help_process.projection
    if help_projection.returncode != 1:
        return "capability-failed", "help-exit", None
    if not _probe_streams_clean(help_projection):
        return "capability-failed", "help-stream", None
    if not parse_help_grammar(help_process.stdout_text or ""):
        return "capability-failed", "help-grammar", None

    list_projection = list_process.projection
    if list_projection.returncode != 0:
        return "capability-failed", "list-exit", None
    if not _probe_streams_clean(list_projection):
        return "capability-failed", "list-stream", None
    try:
        operations = parse_operations(list_process.stdout_text or "")
    except BackendOpsGrammarError:
        return "capability-failed", "list-grammar", None

    advertised = set(operations)
    if any(operation not in advertised for operation in case.operations):
        return "capability-failed", "operation-absent", None

    capabilities = BackendOpsCapabilitiesV1(binary_sha256=binary_sha256, operations=operations)
    return None, None, capabilities


def _classify_test(
    test_process: _ProjectedProcess, *, case: BackendOpsCaseV1
) -> tuple[SampleStatus, tuple[BackendOpsRowV1, ...] | None, BackendOpsGateSummaryV1 | None]:
    """Map the test child's outcome to a terminal status, retained rows, and gate.

    Independently exact stdout is always parsed and its rows retained, even when
    stderr is defective or the child exits nonzero. A process defect on *either*
    stream (capture, spawn, timeout, oversized, invalid UTF-8) outranks child, parse,
    and gate outcomes and forbids a pass, matching the hard-gate condition that a
    passing case has no truncation/encoding defect; a nonzero exit (``child-failed``)
    then wins over parse and gate outcomes.
    """

    projection = test_process.projection

    rows: tuple[BackendOpsRowV1, ...] | None = None
    if projection.stdout_publishable and not projection.stdout_truncated:
        try:
            rows = parse_csv_rows(test_process.stdout_text or "", case=case)
        except BackendOpsParseError:
            rows = None

    if projection.error_category != "none":
        return _DEFECT_STATUS[projection.error_category], rows, None
    if projection.returncode != 0:
        return "child-failed", rows, None
    if rows is None:
        return "parse-failed", None, None
    gate = evaluate_gate(rows, case=case)
    if gate.passed:
        return "passed", rows, gate
    return "hard-gate-failed", rows, gate


# --- Orchestration ------------------------------------------------------------


def run_backend_ops_case(
    *,
    case: BackendOpsCaseV1,
    inputs: BackendOpsInputsV1,
    run: RunSession,
    environment: Mapping[str, str],
    cwd: Path,
    capability_timeout: float,
    test_timeout: float,
    runner: ProcessRunner = run_process,
) -> BackendOpsSampleV1:
    """Execute one correctness case and return its terminal versioned sample.

    Two bounded capability probes and (on capability success) one test child run
    against ``environment`` with ``inherit_env=False`` and an explicit ``cwd``. Binary
    identity is verified before each child and re-verified after the terminal child;
    drift raises :class:`BackendOpsIntegrityError` and leaves no ``sample.json``.
    Ordinary capability, process, parse, and hard-gate failures return a structured
    sample. The caller owns ``run``: this adapter never finalizes it.
    """

    binary_path = Path(inputs.binary_path)
    evidence = _CaseEvidence(run=run, base=f"{EVIDENCE_ROOT}/{case.id}")

    identity = _hash_binary(binary_path)
    if identity.sha256 != inputs.binary_sha256:
        raise BackendOpsIntegrityError("operations binary SHA-256 does not match the input binding")

    # Probe 1: --help. The initial hash snapshot is its integrity check.
    help_process = _run_child(
        runner=runner,
        argv=(str(binary_path), "--help"),
        cwd=cwd,
        timeout=capability_timeout,
        environment=environment,
        evidence=evidence,
        prefix="capabilities/help",
        sep=".",
        stdout_name="stdout.txt",
        stdout_media="text/plain",
    )

    # Probe 2: --list-ops. Always attempted unless intervening drift aborts.
    _require_stable_binary(binary_path, identity)
    list_process = _run_child(
        runner=runner,
        argv=(str(binary_path), "--list-ops"),
        cwd=cwd,
        timeout=capability_timeout,
        environment=environment,
        evidence=evidence,
        prefix="capabilities/list-ops",
        sep=".",
        stdout_name="stdout.txt",
        stdout_media="text/plain",
    )

    status, reason, capabilities = _evaluate_capability(
        help_process, list_process, case=case, binary_sha256=inputs.binary_sha256
    )
    attempt = BackendOpsCapabilityAttemptV1(
        status="failed" if capabilities is None else "discovered",
        reason=reason,
        help=help_process.projection,
        list_ops=list_process.projection,
        capabilities=capabilities,
    )
    evidence.json("capabilities/attempt.json", attempt.model_dump(mode="json"))

    if capabilities is None:
        assert status is not None
        _require_stable_binary(binary_path, identity)
        return _finalize(
            evidence,
            status=status,
            reason=reason,
            case=case,
            inputs=inputs,
            attempt=attempt,
            invocation=None,
            rows=None,
            gate=None,
        )

    # Test child.
    argv = build_test_argv(binary_path=str(binary_path), case=case)
    _require_stable_binary(binary_path, identity)
    test_process = _run_child(
        runner=runner,
        argv=argv,
        cwd=cwd,
        timeout=test_timeout,
        environment=environment,
        evidence=evidence,
        prefix="invocations/0001",
        sep="/",
        stdout_name="stdout.csv",
        stdout_media="text/csv",
    )

    # Re-verify identity after the terminal child. Drift leaves no sample.json.
    _require_stable_binary(binary_path, identity)

    invocation = BackendOpsInvocationV1(ordinal=1, argv=argv, process=test_process.projection)
    test_status, rows, gate = _classify_test(test_process, case=case)
    return _finalize(
        evidence,
        status=test_status,
        reason=None,
        case=case,
        inputs=inputs,
        attempt=attempt,
        invocation=invocation,
        rows=rows,
        gate=gate,
    )


def _finalize(
    evidence: _CaseEvidence,
    *,
    status: SampleStatus,
    reason: CapabilityReason | None,
    case: BackendOpsCaseV1,
    inputs: BackendOpsInputsV1,
    attempt: BackendOpsCapabilityAttemptV1,
    invocation: BackendOpsInvocationV1 | None,
    rows: tuple[BackendOpsRowV1, ...] | None,
    gate: BackendOpsGateSummaryV1 | None,
) -> BackendOpsSampleV1:
    """Build the sample from already-written evidence and publish ``sample.json`` last."""

    sample = BackendOpsSampleV1(
        status=status,
        reason=reason,
        case=case,
        inputs=inputs,
        capability_attempt=attempt,
        capabilities=attempt.capabilities,
        invocation=invocation,
        rows=rows,
        gate=gate,
        artifacts=tuple(sorted(evidence.written, key=lambda artifact: artifact.path)),
    )
    evidence.sample(sample.model_dump(mode="json"))
    return sample
